// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNjMKvl70v-YdGxDStRz2SZXiIKQKF2Y',
    appId: '1:521239215201:web:bf3c84ea6d6c78d965fe20',
    messagingSenderId: '521239215201',
    projectId: 'fitness-journal-apps',
    authDomain: 'fitness-journal-apps.firebaseapp.com',
    storageBucket: 'fitness-journal-apps.appspot.com',
    measurementId: 'G-128LTJ0ND3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGjh6jHyaLsXvZQ-wGsFJRIg6W1eRFwWc',
    appId: '1:521239215201:android:5fd74c919d0a8a9265fe20',
    messagingSenderId: '521239215201',
    projectId: 'fitness-journal-apps',
    storageBucket: 'fitness-journal-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxId6ffg1gdUZJrHWSNM2srakif0krq-k',
    appId: '1:521239215201:ios:71a24d196000210065fe20',
    messagingSenderId: '521239215201',
    projectId: 'fitness-journal-apps',
    storageBucket: 'fitness-journal-apps.appspot.com',
    iosBundleId: 'com.example.fitnessJournal',
  );
}
